f <- system.file("include",package="TMB")
tmb <- unlist(lapply(dir(f,pattern=".hpp",full=TRUE),readLines))
tmb1 <- paste(tmb,collapse="") ## Everything on one line - warning: do not print!
d <- grep("^VECTORIZE.*\\(d", tmb, value=TRUE)
p <- grep("^VECTORIZE.*\\(p", tmb, value=TRUE)
dp <- c(d,p)
dp <- sub("VECTORIZE(.)_(.*)\\((.*)\\)", "\\3 \\1 \\2", dp)
df <- as.data.frame(t(do.call(cbind, sapply(dp, strsplit, " "))), stringsAsFactors=FALSE)
names(df) <- c("name","npar","code")
df <- subset(df,name!="pow") ## bogus
df <- subset(df, !(name=="pnorm" & npar==1) ) ## bogus
skip <- c("pSHASHo")
df <- subset(df, !(name %in% skip))

getsig <- function(name) {
    x <- sub(paste0(".*Type ",name,"\\((.*?)\\).*"),"\\1",tmb1)
    x <- gsub("[ ]*( )","\\1", x)
    x <- gsub("Type ", "", x)
    x <- gsub("const ", "", x)
    x <- gsub("\\&", "", x)
    x <- gsub("\t", "", x)
    x <- gsub("int give_log.*", "give_log", x)
    x[1]
}
df$signature_raw <- sapply(df$name,getsig)
sigtidy <- function(x) {
    x <- gsub("=.*?\\.","",x)
    x <- sub("^k","x",x)
    x <- sub("^y","x",x)
    ##x <- sub("give_log","log",x)
    x <- sub("[ ]*,",",",x)
    x
}
df$signature <- sigtidy(df$signature_raw)
## More tidy
i <- substring(df$name,1,1)=="p"
substring(df$signature[i],1,1) <- "q"
df$stats <- sapply(df$name, exists, "package:stats")
getargs <- function(sig)gsub(" ","",strsplit(sig,",[ ]*")[[1]])

newname <- function(x)paste0("distr_",x)
codegen <- function(i) {
    C <- df$signature[i]; npar <- as.numeric(df$npar[i])
    args <- strsplit(df$signature[i],",[ ]*")[[1]]
    fun <- df$name[i]
    type <- substring(fun,1,1)
    ## Codegen
    adind <- if (type=="d") (1:(npar-1)) else 1:npar
    nk <- paste0("n", adind)
    adargs <- args[adind]
    Xk <- paste0("X", adind)
    c(
    "// [[Rcpp::export]]",
    paste("Rcpp::ComplexVector", newname(fun),"(",paste(c(paste("Rcpp::ComplexVector", adargs ), paste("bool", tail(args,  1))  [type=="d"] ) , collapse=", "),")"),
    "{",
    paste0("int ", nk ,"=", adargs, ".size();"),
    paste0("int nmax = std::max({",paste(nk, collapse=", "),"});"),
    paste0("int nmin = std::min({",paste(nk, collapse=", "),"});"),
    "int n = (nmin == 0 ? 0 : nmax);",
    "Rcpp::ComplexVector ans(n);",
    paste0("const ad* ", Xk, " = adptr(", adargs ,");", collapse=" "),
    "ad* Y = adptr(ans);",
    paste0("for (int i=0; i<n; i++) Y[i] = ",fun, "(",  paste0(Xk, "[i % ", nk, "]", collapse=", "), ", give_log"[type=="d"] ,");"),
    "return as_advector(ans);",
    "}")
}

header <- c(
    "// Autogenerated - do not edit",
    "#include <Rcpp.h>",
    "#include \"TMB.h\"",
    "typedef TMBad::ad_aug ad;",
    "ad* adptr(const Rcpp::ComplexVector &x);",
    "Rcpp::ComplexVector& as_advector(Rcpp::ComplexVector &x);")


## Make all TMB functions available via prefix 'distr_'
code <- unlist(lapply(1:nrow(df), codegen))
txt <- c(header, code)
writeLines(txt, "RTMB/src/distributions.cpp")

## ============================================================
## S4 R interface
df$signature <- sub("give_log","log",df$signature)
string <- function(x)paste0('"',x,'"')
getRmethod <- function(i) {
    name <- df$name[i]
    a1 <- getargs(df$signature[i]) ## short (tmb)
    a2 <- names(head(as.list(args(get(name,"package:stats"))),-1)) ## long (R)
    if(any(is.na(match(a1,a2)))) {
        print(name)
    }
    a2.type <- ifelse(a2 %in% c("log","log.p","lower.tail") , "logical", "advector_castable")
    ans <- ifelse(is.na(match(a2,a1)),"missing",a2.type)
    sig <- paste0("signature(",(paste(a2,"=",string(ans),collapse=", ")),")")
    cast <- ifelse(ans[match(a1,a2)]=="advector_castable","advector","as.logical")
    def <- c(
        paste("function(", df$signature[i],") {"),
        paste(a1, "<- ",cast,"(",a1,")"),
        paste(newname(name),"(",df$signature[i],")"), "}")
    c(paste0("setMethod(", string(name), ","),
      paste0(sig, ","),
      def, ")" )
}
## Start with stats methods only:
header <- c("## Autogenerated - do not edit","")
code <- unlist(lapply(which(df$stats), getRmethod))
txt <- c(header, code)
writeLines(txt, "RTMB/R/distributions.R")
