# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logspace_gamma <- function(x) {
    .Call(`_rtmbXtra_logspace_gamma`, x)
}

logit_invcloglog <- function(x) {
    .Call(`_rtmbXtra_logit_invcloglog`, x)
}

logit_pnorm <- function(x) {
    .Call(`_rtmbXtra_logit_pnorm`, x)
}

