## Autogenerated - do not edit

setMethod("dexp",
signature(x = "ad", rate = "ad.", log = "logical."),
function( x, rate, log ) {
x <-  advector ( x )
rate <-  advector ( rate )
log <-  as.logical ( log )
distr_dexp ( x, rate, log )
}
)
setMethod("dexp",
signature(x = "num", rate = "num.", log = "logical."),
function( x, rate, log ) {
stats:: dexp ( x, rate, log )
}
)
setMethod("dweibull",
signature(x = "ad", shape = "ad", scale = "ad.", log = "logical."),
function( x, shape, scale, log ) {
x <-  advector ( x )
shape <-  advector ( shape )
scale <-  advector ( scale )
log <-  as.logical ( log )
distr_dweibull ( x, shape, scale, log )
}
)
setMethod("dweibull",
signature(x = "num", shape = "num", scale = "num.", log = "logical."),
function( x, shape, scale, log ) {
stats:: dweibull ( x, shape, scale, log )
}
)
setMethod("dbinom",
signature(x = "ad", size = "ad", prob = "ad", log = "logical."),
function( x, size, prob, log ) {
x <-  advector ( x )
size <-  advector ( size )
prob <-  advector ( prob )
log <-  as.logical ( log )
distr_dbinom ( x, size, prob, log )
}
)
setMethod("dbinom",
signature(x = "num", size = "num", prob = "num", log = "logical."),
function( x, size, prob, log ) {
stats:: dbinom ( x, size, prob, log )
}
)
setMethod("dbeta",
signature(x = "ad", shape1 = "ad", shape2 = "ad", ncp = "missing", log = "logical."),
function( x, shape1, shape2, log ) {
x <-  advector ( x )
shape1 <-  advector ( shape1 )
shape2 <-  advector ( shape2 )
log <-  as.logical ( log )
distr_dbeta ( x, shape1, shape2, log )
}
)
setMethod("dbeta",
signature(x = "num", shape1 = "num", shape2 = "num", ncp = "missing", log = "logical."),
function( x, shape1, shape2, log ) {
stats:: dbeta ( x, shape1, shape2, log )
}
)
setMethod("df",
signature(x = "ad", df1 = "ad", df2 = "ad", ncp = "missing", log = "logical."),
function( x, df1, df2, log ) {
x <-  advector ( x )
df1 <-  advector ( df1 )
df2 <-  advector ( df2 )
log <-  as.logical ( log )
distr_df ( x, df1, df2, log )
}
)
setMethod("df",
signature(x = "num", df1 = "num", df2 = "num", ncp = "missing", log = "logical."),
function( x, df1, df2, log ) {
stats:: df ( x, df1, df2, log )
}
)
setMethod("dlogis",
signature(x = "ad", location = "ad.", scale = "ad.", log = "logical."),
function( x, location, scale, log ) {
x <-  advector ( x )
location <-  advector ( location )
scale <-  advector ( scale )
log <-  as.logical ( log )
distr_dlogis ( x, location, scale, log )
}
)
setMethod("dlogis",
signature(x = "num", location = "num.", scale = "num.", log = "logical."),
function( x, location, scale, log ) {
stats:: dlogis ( x, location, scale, log )
}
)
setMethod("dt",
signature(x = "ad", df = "ad", ncp = "missing", log = "logical."),
function( x, df, log ) {
x <-  advector ( x )
df <-  advector ( df )
log <-  as.logical ( log )
distr_dt ( x, df, log )
}
)
setMethod("dt",
signature(x = "num", df = "num", ncp = "missing", log = "logical."),
function( x, df, log ) {
stats:: dt ( x, df, log )
}
)
setMethod("dnbinom",
signature(x = "ad", size = "ad", prob = "ad", mu = "missing", log = "logical."),
function( x, size, prob, log ) {
x <-  advector ( x )
size <-  advector ( size )
prob <-  advector ( prob )
log <-  as.logical ( log )
distr_dnbinom ( x, size, prob, log )
}
)
setMethod("dnbinom",
signature(x = "num", size = "num", prob = "num", mu = "missing", log = "logical."),
function( x, size, prob, log ) {
stats:: dnbinom ( x, size, prob, log )
}
)
setMethod("dpois",
signature(x = "ad", lambda = "ad", log = "logical."),
function( x, lambda, log ) {
x <-  advector ( x )
lambda <-  advector ( lambda )
log <-  as.logical ( log )
distr_dpois ( x, lambda, log )
}
)
setMethod("dpois",
signature(x = "num", lambda = "num", log = "logical."),
function( x, lambda, log ) {
stats:: dpois ( x, lambda, log )
}
)
setMethod("dgamma",
signature(x = "ad", shape = "ad", rate = "missing", scale = "ad.", log = "logical."),
function( x, shape, scale, log ) {
x <-  advector ( x )
shape <-  advector ( shape )
scale <-  advector ( scale )
log <-  as.logical ( log )
distr_dgamma ( x, shape, scale, log )
}
)
setMethod("dgamma",
signature(x = "num", shape = "num", rate = "missing", scale = "num.", log = "logical."),
function( x, shape, scale, log ) {
stats:: dgamma ( x, shape, scale, log )
}
)
setMethod("pnorm",
signature(q = "ad", mean = "ad.", sd = "ad.", lower.tail = "missing", log.p = "missing"),
function( q, mean , sd  ) {
q <-  advector ( q )
mean <-  advector ( mean )
sd <-  advector ( sd )
distr_pnorm ( q, mean , sd  )
}
)
setMethod("pnorm",
signature(q = "num", mean = "num.", sd = "num.", lower.tail = "missing", log.p = "missing"),
function( q, mean , sd  ) {
stats:: pnorm ( q, mean , sd  )
}
)
setMethod("pgamma",
signature(q = "ad", shape = "ad", rate = "missing", scale = "ad.", lower.tail = "missing", log.p = "missing"),
function( q, shape, scale  ) {
q <-  advector ( q )
shape <-  advector ( shape )
scale <-  advector ( scale )
distr_pgamma ( q, shape, scale  )
}
)
setMethod("pgamma",
signature(q = "num", shape = "num", rate = "missing", scale = "num.", lower.tail = "missing", log.p = "missing"),
function( q, shape, scale  ) {
stats:: pgamma ( q, shape, scale  )
}
)
setMethod("ppois",
signature(q = "ad", lambda = "ad", lower.tail = "missing", log.p = "missing"),
function( q, lambda ) {
q <-  advector ( q )
lambda <-  advector ( lambda )
distr_ppois ( q, lambda )
}
)
setMethod("ppois",
signature(q = "num", lambda = "num", lower.tail = "missing", log.p = "missing"),
function( q, lambda ) {
stats:: ppois ( q, lambda )
}
)
setMethod("pexp",
signature(q = "ad", rate = "ad.", lower.tail = "missing", log.p = "missing"),
function( q, rate ) {
q <-  advector ( q )
rate <-  advector ( rate )
distr_pexp ( q, rate )
}
)
setMethod("pexp",
signature(q = "num", rate = "num.", lower.tail = "missing", log.p = "missing"),
function( q, rate ) {
stats:: pexp ( q, rate )
}
)
setMethod("pweibull",
signature(q = "ad", shape = "ad", scale = "ad.", lower.tail = "missing", log.p = "missing"),
function( q, shape, scale ) {
q <-  advector ( q )
shape <-  advector ( shape )
scale <-  advector ( scale )
distr_pweibull ( q, shape, scale )
}
)
setMethod("pweibull",
signature(q = "num", shape = "num", scale = "num.", lower.tail = "missing", log.p = "missing"),
function( q, shape, scale ) {
stats:: pweibull ( q, shape, scale )
}
)
setMethod("pbeta",
signature(q = "ad", shape1 = "ad", shape2 = "ad", ncp = "missing", lower.tail = "missing", log.p = "missing"),
function( q, shape1, shape2 ) {
q <-  advector ( q )
shape1 <-  advector ( shape1 )
shape2 <-  advector ( shape2 )
distr_pbeta ( q, shape1, shape2 )
}
)
setMethod("pbeta",
signature(q = "num", shape1 = "num", shape2 = "num", ncp = "missing", lower.tail = "missing", log.p = "missing"),
function( q, shape1, shape2 ) {
stats:: pbeta ( q, shape1, shape2 )
}
)
