# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

valid <- function(x) {
    .Call(`_RTMB_valid`, x)
}

ad_context <- function() {
    .Call(`_RTMB_ad_context`)
}

as_advector <- function(x) {
    .Call(`_RTMB_as_advector`, x)
}

force_update <- function(adf) {
    invisible(.Call(`_RTMB_force_update`, adf))
}

SpJacFun <- function(adf) {
    .Call(`_RTMB_SpJacFun`, adf)
}

RangeProj <- function(adf, i) {
    invisible(.Call(`_RTMB_RangeProj`, adf, i))
}

find_op_by_name <- function(adf, name) {
    .Call(`_RTMB_find_op_by_name`, adf, name)
}

op2var <- function(adf, nodes) {
    .Call(`_RTMB_op2var`, adf, nodes)
}

findIndex <- function(adf, name) {
    .Call(`_RTMB_findIndex`, adf, name)
}

setinvIndex <- function(adf, index) {
    invisible(.Call(`_RTMB_setinvIndex`, adf, index))
}

getinvIndex <- function(adf) {
    .Call(`_RTMB_getinvIndex`, adf)
}

get_graph <- function(adf) {
    .Call(`_RTMB_get_graph`, adf)
}

get_df <- function(adf) {
    .Call(`_RTMB_get_df`, adf)
}

timer <- function(adf, rep = 1L) {
    .Call(`_RTMB_timer`, adf, rep)
}

get_node <- function(adf, node) {
    invisible(.Call(`_RTMB_get_node`, adf, node))
}

set_tape_config <- function(matmul = "NA", ops = "NA", math = "NA", sum = "NA", mvnorm = "NA", compare = "NA") {
    .Call(`_RTMB_set_tape_config`, matmul, ops, math, sum, mvnorm, compare)
}

compare_allow <- function() {
    .Call(`_RTMB_compare_allow`)
}

ad_mapply <- function(tp, args) {
    .Call(`_RTMB_ad_mapply`, tp, args)
}

advec <- function(x) {
    .Call(`_RTMB_advec`, x)
}

dependent <- function(x) {
    .Call(`_RTMB_dependent`, x)
}

independent <- function(x) {
    .Call(`_RTMB_independent`, x)
}

resolve_refs <- function(adf) {
    .Call(`_RTMB_resolve_refs`, adf)
}

decompose_refs <- function(adf) {
    invisible(.Call(`_RTMB_decompose_refs`, adf))
}

getValues <- function(x) {
    .Call(`_RTMB_getValues`, x)
}

getVariables <- function(x) {
    .Call(`_RTMB_getVariables`, x)
}

dbgprint <- function(x) {
    invisible(.Call(`_RTMB_dbgprint`, x))
}

ptr_getx <- function(adf) {
    .Call(`_RTMB_ptr_getx`, adf)
}

ptr_gety <- function(adf) {
    .Call(`_RTMB_ptr_gety`, adf)
}

distr_besselK <- function(x, nu, expo = FALSE) {
    .Call(`_RTMB_distr_besselK`, x, nu, expo)
}

distr_besselI <- function(x, nu, expo = FALSE) {
    .Call(`_RTMB_distr_besselI`, x, nu, expo)
}

distr_besselJ <- function(x, nu) {
    .Call(`_RTMB_distr_besselJ`, x, nu)
}

distr_besselY <- function(x, nu) {
    .Call(`_RTMB_distr_besselY`, x, nu)
}

distr_dexp <- function(x, rate, give_log) {
    .Call(`_RTMB_distr_dexp`, x, rate, give_log)
}

distr_dweibull <- function(x, shape, scale, give_log) {
    .Call(`_RTMB_distr_dweibull`, x, shape, scale, give_log)
}

distr_dbinom <- function(x, size, prob, give_log) {
    .Call(`_RTMB_distr_dbinom`, x, size, prob, give_log)
}

distr_dbinom_robust <- function(x, size, logit_p, give_log) {
    .Call(`_RTMB_distr_dbinom_robust`, x, size, logit_p, give_log)
}

distr_dbeta <- function(x, shape1, shape2, give_log) {
    .Call(`_RTMB_distr_dbeta`, x, shape1, shape2, give_log)
}

distr_df <- function(x, df1, df2, give_log) {
    .Call(`_RTMB_distr_df`, x, df1, df2, give_log)
}

distr_dlogis <- function(x, location, scale, give_log) {
    .Call(`_RTMB_distr_dlogis`, x, location, scale, give_log)
}

distr_dsn <- function(x, alpha, give_log) {
    .Call(`_RTMB_distr_dsn`, x, alpha, give_log)
}

distr_dt <- function(x, df, give_log) {
    .Call(`_RTMB_distr_dt`, x, df, give_log)
}

distr_dSHASHo <- function(x, mu, sigma, nu, tau, give_log) {
    .Call(`_RTMB_distr_dSHASHo`, x, mu, sigma, nu, tau, give_log)
}

distr_dtweedie <- function(x, mu, phi, p, give_log) {
    .Call(`_RTMB_distr_dtweedie`, x, mu, phi, p, give_log)
}

distr_dnbinom <- function(x, size, prob, give_log) {
    .Call(`_RTMB_distr_dnbinom`, x, size, prob, give_log)
}

distr_dnbinom_robust <- function(x, log_mu, log_var_minus_mu, give_log) {
    .Call(`_RTMB_distr_dnbinom_robust`, x, log_mu, log_var_minus_mu, give_log)
}

distr_dnbinom2 <- function(x, mu, var, give_log) {
    .Call(`_RTMB_distr_dnbinom2`, x, mu, var, give_log)
}

distr_dpois <- function(x, lambda, give_log) {
    .Call(`_RTMB_distr_dpois`, x, lambda, give_log)
}

distr_dgamma <- function(x, shape, scale, give_log) {
    .Call(`_RTMB_distr_dgamma`, x, shape, scale, give_log)
}

distr_dlgamma <- function(x, shape, scale, give_log) {
    .Call(`_RTMB_distr_dlgamma`, x, shape, scale, give_log)
}

distr_pnorm <- function(q, mean, sd) {
    .Call(`_RTMB_distr_pnorm`, q, mean, sd)
}

distr_pgamma <- function(q, shape, scale) {
    .Call(`_RTMB_distr_pgamma`, q, shape, scale)
}

distr_ppois <- function(q, lambda) {
    .Call(`_RTMB_distr_ppois`, q, lambda)
}

distr_pexp <- function(q, rate) {
    .Call(`_RTMB_distr_pexp`, q, rate)
}

distr_pweibull <- function(q, shape, scale) {
    .Call(`_RTMB_distr_pweibull`, q, shape, scale)
}

distr_pbeta <- function(q, shape1, shape2) {
    .Call(`_RTMB_distr_pbeta`, q, shape1, shape2)
}

distr_qnorm <- function(p, mean, sd) {
    .Call(`_RTMB_distr_qnorm`, p, mean, sd)
}

distr_qgamma <- function(p, shape, scale) {
    .Call(`_RTMB_distr_qgamma`, p, shape, scale)
}

distr_qexp <- function(p, rate) {
    .Call(`_RTMB_distr_qexp`, p, rate)
}

distr_qweibull <- function(p, shape, scale) {
    .Call(`_RTMB_distr_qweibull`, p, shape, scale)
}

distr_qbeta <- function(p, shape1, shape2) {
    .Call(`_RTMB_distr_qbeta`, p, shape1, shape2)
}

distr_compois_calc_logZ <- function(loglambda, nu) {
    .Call(`_RTMB_distr_compois_calc_logZ`, loglambda, nu)
}

distr_compois_calc_loglambda <- function(logmean, nu) {
    .Call(`_RTMB_distr_compois_calc_loglambda`, logmean, nu)
}

distr_lbeta <- function(a, b) {
    .Call(`_RTMB_distr_lbeta`, a, b)
}

distr_logspace_add <- function(logx, logy) {
    .Call(`_RTMB_distr_logspace_add`, logx, logy)
}

distr_logspace_sub <- function(logx, logy) {
    .Call(`_RTMB_distr_logspace_sub`, logx, logy)
}

distr_rcompois <- function(loglambda, nu) {
    .Call(`_RTMB_distr_rcompois`, loglambda, nu)
}

expATv <- function(AT, v, N, C, cfg, cache) {
    .Call(`_RTMB_expATv`, AT, v, N, C, cfg, cache)
}

bisect_atom <- function(adf, x_, cfg) {
    .Call(`_RTMB_bisect_atom`, adf, x_, cfg)
}

ip2D <- function(data, x_range, y_range, con) {
    .Call(`_RTMB_ip2D`, data, x_range, y_range, con)
}

ip2D_eval_num <- function(ptr, x, y) {
    .Call(`_RTMB_ip2D_eval_num`, ptr, x, y)
}

ip2D_eval_ad <- function(ptr, x, y) {
    .Call(`_RTMB_ip2D_eval_ad`, ptr, x, y)
}

splineptr <- function(x, y, method = 3L) {
    .Call(`_RTMB_splineptr`, x, y, method)
}

splineptr_eval <- function(ptr, x) {
    .Call(`_RTMB_splineptr_eval`, ptr, x)
}

sytrisol <- function(L, W) {
    .Call(`_RTMB_sytrisol`, L, W)
}

Arith2 <- function(x, y, op) {
    .Call(`_RTMB_Arith2`, x, y, op)
}

Math1 <- function(x, op) {
    .Call(`_RTMB_Math1`, x, op)
}

math_atan2 <- function(y, x) {
    .Call(`_RTMB_math_atan2`, y, x)
}

Reduce1 <- function(x, op) {
    .Call(`_RTMB_Reduce1`, x, op)
}

matmul <- function(x, y) {
    .Call(`_RTMB_matmul`, x, y)
}

matinv <- function(x) {
    .Call(`_RTMB_matinv`, x)
}

dmvnorm0 <- function(x, s, give_log, keep = NULL) {
    .Call(`_RTMB_dmvnorm0`, x, s, give_log, keep)
}

dgmrf0 <- function(x, q, give_log) {
    .Call(`_RTMB_dgmrf0`, x, q, give_log)
}

SparseArith2 <- function(x, y, op) {
    .Call(`_RTMB_SparseArith2`, x, y, op)
}

Dense2Sparse <- function(x) {
    .Call(`_RTMB_Dense2Sparse`, x)
}

math_expm <- function(x) {
    .Call(`_RTMB_math_expm`, x)
}

math_sqrtm <- function(x) {
    .Call(`_RTMB_math_sqrtm`, x)
}

math_absm <- function(x) {
    .Call(`_RTMB_math_absm`, x)
}

SparseSolve <- function(s, x) {
    .Call(`_RTMB_SparseSolve`, s, x)
}

fft_complex <- function(x, dim, inverse = FALSE) {
    .Call(`_RTMB_fft_complex`, x, dim, inverse)
}

TapedEval <- function(F, i) {
    .Call(`_RTMB_TapedEval`, F, i)
}

reorder_transform <- function(adf, last) {
    invisible(.Call(`_RTMB_reorder_transform`, adf, last))
}

set_tail_transform <- function(adf, last) {
    invisible(.Call(`_RTMB_set_tail_transform`, adf, last))
}

LowRankTag <- function(x) {
    .Call(`_RTMB_LowRankTag`, x)
}

Term <- function(x_) {
    .Call(`_RTMB_Term`, x_)
}

TermsZero <- function(adf, setZero) {
    invisible(.Call(`_RTMB_TermsZero`, adf, setZero))
}

InvPersistent <- function(adf, setPers) {
    invisible(.Call(`_RTMB_InvPersistent`, adf, setPers))
}

subset_ad <- function(x, i) {
    .Call(`_RTMB_subset_ad`, x, i)
}

findInterval_ad <- function(x, i) {
    .Call(`_RTMB_findInterval_ad`, x, i)
}

order_ad <- function(x) {
    .Call(`_RTMB_order_ad`, x)
}

sort_ad <- function(x) {
    .Call(`_RTMB_sort_ad`, x)
}

