# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

valid <- function(x) {
    .Call(`_RTMB_valid`, x)
}

ad_context <- function() {
    .Call(`_RTMB_ad_context`)
}

advec <- function(x) {
    .Call(`_RTMB_advec`, x)
}

dependent <- function(x) {
    .Call(`_RTMB_dependent`, x)
}

independent <- function(x) {
    .Call(`_RTMB_independent`, x)
}

Arith2 <- function(x, y, op) {
    .Call(`_RTMB_Arith2`, x, y, op)
}

Math1 <- function(x, op) {
    .Call(`_RTMB_Math1`, x, op)
}

Reduce1 <- function(x, op) {
    .Call(`_RTMB_Reduce1`, x, op)
}

getValues <- function(x) {
    .Call(`_RTMB_getValues`, x)
}

getVariables <- function(x) {
    .Call(`_RTMB_getVariables`, x)
}

dbgprint <- function(x) {
    invisible(.Call(`_RTMB_dbgprint`, x))
}

matmul <- function(x, y, method) {
    .Call(`_RTMB_matmul`, x, y, method)
}

dmvnorm0 <- function(x, s, give_log) {
    .Call(`_RTMB_dmvnorm0`, x, s, give_log)
}

dgmrf0 <- function(x, q, give_log) {
    .Call(`_RTMB_dgmrf0`, x, q, give_log)
}

SparseArith2 <- function(x, y, op) {
    .Call(`_RTMB_SparseArith2`, x, y, op)
}

