## Check consistency of some models using automatic simulation feature
## (takes a few minutes)
source("transform.R")
chk1 <- checkConsistency(obj)
source("transform2.R")
chk2 <- checkConsistency(obj)
source("sdv_multi.R")
system.time(chk3 <- checkConsistency(obj))
source("tweedie.R")
system.time(chk4 <- checkConsistency(model))
##
(chk1)
(chk2)
(chk3)
(chk4)
